# Dependencies
#markdown:         redcarpet
#pygments:         true
#markdown:          kramdown
#highlighter:       rouge
# Permalinks
permalink:        pretty

# Setup
title:            Anuradha Uduwage
tagline:          'The personal website of Anuradha Uduwage'
description:      'The personal website of Anuradha Uduwage'
url:              http://uduwage.github.io/


author:
  name:           'Anuradha Uduwage'
  url:            https://twitter.com/colombounplug

paginate:         1
#baseurl:          /

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/uduwage/uduwage.github.io

# This is the list of pages to incldue in the header of the website.
pages_list:       {'Experience':'/experience','Publications':'/publications','Archive':'/archive','About':'/about', 'Feed':'/atom.xml'}