# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Anuradha Uduwage
tagline:          'The personal website of Anuradha Uduwage'
description:      'The personal website of Anuradha Uduwage'
url:              http://uduwage.github.io/uduwage/

author:
  name:           'Anuradha Uduwage'
  url:            https://twitter.com/colombounplug

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           github.com/uduwage/uduwage.github.io

# This is the list of pages to incldue in the header of the website.
pages_list:       {'About':'/about', 'Experience':'/experience','Publications':'/publications','Archive':'/archive','Feed':'/atom.xml'}